### ISSUE TITLE
Stderr: VBoxManage.exe: error: RawFile#0 failed to create the raw output file ../ubuntu-xenial-16.04-cloudimg-console.log (VERR_PATH_NOT_FOUND)

### ISSUE THREAD

**Issue by joelhandwell** [joelhandwell/ubuntu_vagrant_boxes#1]
Getting following error during vagrant up for 16
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "6333f19c-adb9-4bfb-a72d-0c3aecc4d9f7", "--type", "headless"]

Stderr: VBoxManage.exe: error: RawFile#0 failed to create the raw output file D:/code/oss/vbox/u16/ubuntu-xenial-16.04-cloudimg-console.log (VERR_PATH_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```

**Comment by clarking** [comment]
i was facing the same issue and resolved it by turning off the serial port in the virtualbox configuration, alternatively if you need the serial port, you can leave it enabled but change the log file path to match your filesystem

**Comment by joelhandwell** [comment]
> resolved it by turning off the serial port 

@clarking Right. I ended up set ```--uartmode1``` to ```disconnected``` like following. Not sure if this means turning off but I got solved this issue. Thank you for advice.

```ruby
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
    # Basebox ubuntu/xenial64 comes with following Vagrantfile config and causes https://github.com/joelhandwell/ubuntu_vagrant_boxes/issues/1
    # vb.customize [ "modifyvm", :id, "--uart1", "0x3F8", "4" ]
    # vb.customize [ "modifyvm", :id, "--uartmode1", "file", File.join(Dir.pwd, "ubuntu-xenial-16.04-cloudimg-console.log") ]
    # following config will address the issue
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
end
```
https://github.com/joelhandwell/ubuntu_vagrant_boxes/blob/master/u16/Vagrantfile#L11

**Comment by dushyant8858** [comment]
Thank you so much! It worked for me

**Comment by olvresc** [comment]
Thank you for this! Working fine now when I created a vagrant package and use the box in another device. Experienced this since I'm using ubuntu/xenial64 from cloud and created a package to run on different device.

**Comment by terrylinooo** [comment]
If above answers not work for you, you might try

```
v.customize ["modifyvm", :id, "--cableconnected1", "off"]
```

**Comment by samfullman** [comment]
v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

did not work for me.  What I am seeing is that, from before I ever packaged my Vagrant box, it was wanting that file in a path that was unique to the computer I created it on.  Move that file (or try and install the box on a computer that couldn't have that path) and the vagrant up failed.  Where do I change the SETTINGS of where that raw output file is to be considered present?

**Comment by sanzenwin** [comment]
> > resolved it by turning off the serial port
> 
> @clarking Right. I ended up set `--uartmode1` to `disconnected` like following. Not sure if this means turning off but I got solved this issue. Thank you for advice.
> 
> ```ruby
>   config.vm.provider "virtualbox" do |v|
>     v.memory = 4096
>     v.cpus = 4
>     # Basebox ubuntu/xenial64 comes with following Vagrantfile config and causes https://github.com/joelhandwell/ubuntu_vagrant_boxes/issues/1
>     # vb.customize [ "modifyvm", :id, "--uart1", "0x3F8", "4" ]
>     # vb.customize [ "modifyvm", :id, "--uartmode1", "file", File.join(Dir.pwd, "ubuntu-xenial-16.04-cloudimg-console.log") ]
>     # following config will address the issue
>     v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
> end
> ```
> 
> https://github.com/joelhandwell/ubuntu_vagrant_boxes/blob/master/u16/Vagrantfile#L11

Nice !

**Comment by tanuj-05** [comment]
> ```ruby
> v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
> ```

I did this and the issue got solved, but now I'm facing a different issue.  I'm getting a Warning: Connection refused prompt :

![image](https://user-images.githubusercontent.com/36896851/133636233-45560d26-d191-4567-8a7a-146929cc2c50.png)

**Comment by sspTest** [comment]
@tanuj-05 : I had the same problem and could resolve the error by changing the port number in vagrant file
`config.vm.network "forwarded_port", guest: 22, host: 8022`

**Comment by lahuman** [comment]
> I did this and the issue got solved, but now I'm facing a different issue. I'm getting a Warning: Connection refused prompt :

I think you need this

```
# Install virtualbox_WSL2 plugin
vagrant plugin install virtualbox_WSL2
```
You can check the source code at:
- https://github.com/Karandash8/virtualbox_WSL2

reference : 
https://blog.thenets.org/how-to-run-vagrant-on-wsl-2/?fbclid=IwAR15-DNQzx2am2wU9wZnBlrZo2-hsllf7sKYQ1eoGNgZ4lJTJp30vVvcIqo
